model:
  base_learning_rate: 5e-6
  target: taming.models.vqdiff3.VQDiffModel3
  params:
    embed_dim: 256
    n_embed: 1024
    encconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      mid_input_channel_mult: [1, 1, 1, 2, 2]
      num_res_blocks: 2
      attn_resolutions: [16]
      double_large_kernel: True
      dropout: 0.0
    decconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128 
      ch_mult: [4,2, 2, 1, 1]  # num_up = len(ch_mult)-1
      mid_input_channel_mult: [2, 2, 1, 1, 1]
      num_res_blocks: 2
      attn_resolutions: [16]
      double_large_kernel: True
      dropout: 0.0
    branch_encconfig:
      double_z: False
      z_channels: 256
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult: [ 1,1,2,2,4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [16]
      double_large_kernel: True
      dropout: 0.0

    lossconfig:
      target: taming.modules.losses.VQL1loss.VQL1GradmaskPerceptualloss
      params:
        codebook_weight: 1.0
        use_grad: False
        use_percep: False
        perceptual_weight: 0.0
        pixelloss_weight: 1.0
        gradloss_weight: 0.0

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 4
    num_workers: 8
    train:
      target: taming.data.frame_diff.FrameDiffTarIterDataset
      params:
        tarpath: /dataset/fd5061f6/HWY/cogdata_video/cogdata_task_video17frame_tar/howto100m_animal/howto100m_animal.tar.part_0.cogdata
    validation:
      target: taming.data.frame_diff.FrameDiffTarIterDataset
      params:
        tarpath: /dataset/fd5061f6/HWY/cogdata_video/cogdata_task_video17frame_tar/howto100m_animal/howto100m_animal.tar.part_1.cogdata

# use frame2-frame1 as ground truth